# Helm Values Specific to Products Microservice
configMapData:
  API_PORT: "31200"
  PORT_SERVER: "8080"

  DATABASE_HOST: products-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: "products"
  DATABASE_USER: "postgres"
  DATABASE_DIALECT: "postgres"

secret:
  enabled: true
  data:
    DATABASE_PASSWORD: "TVRJek5EVTI="

externalServices:
  - name: products-db
    externalName: products-database.ccyadp9cu3n9.us-east-1.rds.amazonaws.com

image:
  repository: "045628470274.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-lanchonete/products"
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

database:
  useStatefulSet: false

replicaCount: 1
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "200m"